In [1]:
import torch
import pickle

In [2]:
PATH='/home/kirana/Documents/phd/exp3_autoencoder'
DATAPATH='/home/kirana/Documents/final_dissertation_final/experiments/datasets/bookcrossing'

In [6]:
embed_cat=torch.load(f'{DATAPATH}/inter/save')

RuntimeError: unexpected EOF, expected 8 more bytes. The file might be corrupted.

In [7]:
embed_cat

[tensor([[ 0.1153,  0.3208, -0.1078,  ..., -0.2167,  0.0388,  0.2969],
         [ 0.1642,  0.2022,  0.0683,  ..., -0.1179,  1.3301,  1.5515],
         [ 0.8645,  0.3890, -0.2696,  ...,  0.0000,  0.6350,  2.0225],
         ...,
         [ 0.4900, -0.2705,  0.6921,  ...,  0.3082,  0.4541, -1.1250],
         [ 0.6512, -0.2141,  0.6010,  ..., -0.1124, -0.4912,  0.7047],
         [-0.5154,  1.0701, -0.0215,  ..., -0.5124, -1.4318, -0.1087]],
        device='cuda:1', requires_grad=True),
 tensor([[-1.7680e-01, -3.1324e-01, -5.2745e-02,  ...,  2.6785e-01,
          -1.1699e+00, -2.0678e-01],
         [-3.6085e-01, -5.2789e-01,  0.0000e+00,  ...,  1.8047e-01,
           1.2261e-01,  1.5264e-01],
         [ 3.9582e-33,  7.0006e-38,  4.6242e-38,  ...,  6.2081e-38,
          -4.3766e-38, -3.7634e-40],
         ...,
         [-3.6085e-01, -5.2789e-01,  1.5875e+00,  ...,  1.8047e-01,
           1.2261e-01,  1.5264e-01],
         [ 2.0543e-01,  1.9815e-01, -2.0437e-01,  ..., -1.9504e-01,
          -

In [8]:
import pickle

In [14]:
[Xb,Yb,cat]=pickle.load(open(f'{DATAPATH}/inter/savepickle','rb'))

In [15]:
cat

[tensor([[ 0.0734,  0.5544, -0.7144,  ...,  0.7724, -1.7400,  0.1521],
         [-0.2454,  0.6980, -0.1192,  ..., -0.5076,  0.0649,  0.5186],
         [-0.4472,  0.4082,  0.0255,  ..., -0.2435, -0.1126, -1.0497],
         ...,
         [-1.4932, -0.3306,  1.0294,  ...,  0.7273,  0.2317,  0.1463],
         [-1.3266,  1.3181,  0.7866,  ...,  0.7082,  0.7080,  0.7244],
         [ 0.1996, -1.1800,  1.8188,  ..., -1.2505,  0.4312,  1.6152]],
        device='cuda:1', requires_grad=True),
 tensor([[ 2.0727e-01, -1.7181e-01,  9.5390e-02,  ..., -1.8019e-01,
          -1.3222e-02,  1.7313e-01],
         [-1.5159e-01,  1.7634e-01,  1.4021e-01,  ..., -1.9187e-01,
          -1.9104e-01,  3.5715e-02],
         [-8.7742e-01, -2.8026e-01,  1.1513e-01,  ...,  2.7013e-01,
          -8.6541e-04,  9.8431e-01],
         ...,
         [-4.7534e-38,  4.0832e-38,  3.9684e-38,  ...,  2.5294e-38,
          -2.2380e-38, -4.0507e-38],
         [-1.5409e-01, -1.1428e-01,  3.5513e-02,  ...,  2.3826e-01,
          -

In [16]:
Xb

tensor([[5.6350e+03, 9.1550e+04, 1.5691e+00,  ..., 6.9645e+04, 3.4457e+04,
         7.1230e+03],
        [3.1920e+04, 1.4818e+05, 1.5691e+00,  ..., 1.0976e+05, 7.2600e+02,
         1.5000e+01],
        [1.0991e+04, 1.5132e+05, 1.5691e+00,  ..., 1.2810e+03, 4.3900e+02,
         1.0000e+01],
        ...,
        [8.9500e+02, 1.8179e+05, 1.5691e+00,  ..., 1.3272e+05, 6.0973e+04,
         1.9300e+03],
        [1.1639e+04, 5.0740e+03, 1.5691e+00,  ..., 4.3380e+03, 2.4980e+03,
         7.5000e+01],
        [5.1935e+04, 1.8135e+05, 1.5694e+00,  ..., 1.2864e+05, 1.3020e+03,
         2.7600e+02]], device='cuda:1')

In [19]:
Xb.sum(1)

tensor([209103.0469, 292772.0312, 169018.0469,  18694.7148, 257268.0469,
         74506.0469,  32338.0391,  26790.0391, 158175.0469, 234212.7500,
        306678.7188,  43426.0391, 450212.0312, 301694.0312,  49056.0391,
        160358.0469, 107370.0391, 364163.3750,   6679.5293, 126033.0312,
         22559.0391, 240976.8594, 218273.0469, 209430.0469,  86859.7578,
          3010.0420, 189629.0312, 248205.7031, 402390.8750,  89310.0469,
        261190.0469,   3613.0420,  30313.0391, 120296.7188,  55337.0391,
         99015.0391, 382867.0312, 111939.0547,  49478.0391,  35698.0391,
        186406.1094, 106272.0391,  51671.0391, 243577.0469, 188304.0312,
         19187.0391, 205703.0625,  81026.8125,  10276.8740,  63844.9062,
        186122.0469,  88411.0547,  18047.0410, 310587.0312,  12834.0420,
          5643.0415, 107315.7422, 128834.0469, 178755.7031, 116093.0547,
        179437.0469, 379013.9062,  24645.0391, 363744.0312], device='cuda:1')

In [17]:
Yb

tensor([[ 5.],
        [ 6.],
        [ 4.],
        [ 7.],
        [ 8.],
        [10.],
        [ 9.],
        [ 5.],
        [ 9.],
        [10.],
        [ 6.],
        [10.],
        [ 3.],
        [ 8.],
        [ 7.],
        [ 9.],
        [ 7.],
        [ 8.],
        [ 8.],
        [ 9.],
        [ 8.],
        [ 9.],
        [ 5.],
        [ 6.],
        [10.],
        [ 8.],
        [ 8.],
        [ 8.],
        [ 5.],
        [ 7.],
        [ 6.],
        [10.],
        [ 8.],
        [ 9.],
        [ 8.],
        [ 8.],
        [10.],
        [ 1.],
        [10.],
        [10.],
        [ 8.],
        [ 9.],
        [ 3.],
        [ 8.],
        [ 5.],
        [ 8.],
        [10.],
        [ 8.],
        [ 1.],
        [ 6.],
        [ 6.],
        [ 7.],
        [ 9.],
        [ 9.],
        [ 1.],
        [ 8.],
        [ 7.],
        [10.],
        [ 6.],
        [ 9.],
        [ 8.],
        [10.],
        [ 5.],
        [ 7.]], device='cuda:1')

In [20]:
cat

[tensor([[ 0.0734,  0.5544, -0.7144,  ...,  0.7724, -1.7400,  0.1521],
         [-0.2454,  0.6980, -0.1192,  ..., -0.5076,  0.0649,  0.5186],
         [-0.4472,  0.4082,  0.0255,  ..., -0.2435, -0.1126, -1.0497],
         ...,
         [-1.4932, -0.3306,  1.0294,  ...,  0.7273,  0.2317,  0.1463],
         [-1.3266,  1.3181,  0.7866,  ...,  0.7082,  0.7080,  0.7244],
         [ 0.1996, -1.1800,  1.8188,  ..., -1.2505,  0.4312,  1.6152]],
        device='cuda:1', requires_grad=True),
 tensor([[ 2.0727e-01, -1.7181e-01,  9.5390e-02,  ..., -1.8019e-01,
          -1.3222e-02,  1.7313e-01],
         [-1.5159e-01,  1.7634e-01,  1.4021e-01,  ..., -1.9187e-01,
          -1.9104e-01,  3.5715e-02],
         [-8.7742e-01, -2.8026e-01,  1.1513e-01,  ...,  2.7013e-01,
          -8.6541e-04,  9.8431e-01],
         ...,
         [-4.7534e-38,  4.0832e-38,  3.9684e-38,  ...,  2.5294e-38,
          -2.2380e-38, -4.0507e-38],
         [-1.5409e-01, -1.1428e-01,  3.5513e-02,  ...,  2.3826e-01,
          -